apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: e-commerce-api
  name: payments-deployment
  labels:
    app: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: payments-api
        resources:
            requests:
              cpu: "0.125"
              memory: "16M"
            limits:
              cpu: "0.25"
              memory: "32M"
