apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: e-commerce-api
  name: core-deployment
  labels:
    app: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
      - name: core
        image: core-api
        resources:
            requests:
              cpu: "0.125"
              memory: "16M"
            limits:
              cpu: "0.25"
              memory: "32M"
