apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: e-commerce-api
  name: orders-deployment
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: orders-api
        resources:
            requests:
              cpu: "0.125"
              memory: "16M"
            limits:
              cpu: "0.25"
              memory: "32M"
