apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: e-commerce-api
  name: customers-deployment
  labels:
    app: customers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
      - name: customers
        image: customers-api
        resources:
            requests:
              cpu: "0.125"
              memory: "16M"
            limits:
              cpu: "0.25"
              memory: "32M"
